config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  # 認証
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  delete '/logout', to: 'sessions#destroy'
  
  # 書籍
  resources :books, only: [:index] do
    collection do
      get 'search'
    end
  end
  
  # 所有
  resources :ownerships, only: [:show, :create, :destroy] do
    member do
      patch 'update_categories'
    end
  end
  
  # ユーザー
  resources :users, only: [:index, :show]
  
  # API
  namespace :api do
    resources :categories, only: [:index, :destroy]
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title= content_for(:title) || 'Popondana'
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }/
    %meta{ content: 'yes', name: 'apple-mobile-web-app-capable' }/
    %meta{ content: 'yes', name: 'mobile-web-app-capable' }/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{ href: '/icon.png', rel: 'icon', type: 'image/png' }/
    %link{ href: '/icon.svg', rel: 'icon', type: 'image/svg+xml' }/
    %link{ href: '/icon.png', rel: 'apple-touch-icon' }/
    = stylesheet_link_tag :app, 'data-turbo-track': 'reload'
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css", rel: "stylesheet"}
    %link{href: "https://cdn.jsdelivr.net/npm/tom-select@2.3.1/dist/css/tom-select.css", rel: "stylesheet"}
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
    %script{src: 'https://cdn.jsdelivr.net/npm/chart.js'}
    %script{src: 'https://cdn.jsdelivr.net/npm/tom-select@2.3.1/dist/js/tom-select.complete.min.js'}
  %body
    %header.navbar.navbar-expand-lg.navbar-light.bg-light.mb-4
      .container
        = link_to "Popondana", root_path, class: "navbar-brand"

        - if logged_in?
          %button.navbar-toggler{type: "button", data: {bs: {toggle: "collapse", target: "#navbarNav"}}, aria: {controls: "navbarNav", expanded: "false", label: "Toggle navigation"}}
            %span.navbar-toggler-icon

          #navbarNav.collapse.navbar-collapse
            %ul.navbar-nav.me-auto
              %li.nav-item
                = link_to "所有書籍一覧", books_path, class: "nav-link"
              %li.nav-item
                = link_to "書籍検索", search_books_path, class: "nav-link"
              %li.nav-item
                = link_to "ユーザー一覧", users_path, class: "nav-link"

            .navbar-nav.ms-auto
              %span.navbar-text.me-3
                こんにちは、#{current_user.name}さん
              = link_to "ログアウト", logout_path, data: { 'turbo-method': :delete }, class: "btn btn-outline-secondary btn-sm"
        - else
          .navbar-nav.ms-auto
            = link_to "/auth/google_oauth2", data: { 'turbo-method': :post }, class: "btn btn-primary" do
              %i.bi.bi-google.me-2
              Googleでログイン

    %main.container
      = render 'shared/flash_messages'
      = yield